---
title: "Analysis report for Project 4 in Surf64 summer school"
author: "Nikita, Sebastian"
date: '2018/06/25'
output: html_document
---

## Merging data
# Specify your dataset location
```{r data_folder}
dataset_folder <- file.path("./../dataset/")
```

```{r load_raw_datasets, eval=FALSE}
# Enable eval if needed

# *.txt
covariates <- read.table(file.path(dataset_folder,"Covariates.txt"))
exposures <- read.table(file.path(dataset_folder,"Exposures.txt"))
metabolities <- read.table(file.path(dataset_folder,"Metabolites.txt"))
proteins <- read.table(file.path(dataset_folder,"Proteins.txt"))

# *.rds
methylation <- readRDS(file.path(dataset_folder,"Methylation.rds"))
transcripts <- readRDS(file.path(dataset_folder,"Transcripts.rds"))
raw_data <- list(covariates=covariates,exposures=exposures,metabolities=metabolities,
                 methylation=methylation,proteins=proteins,transcripts=transcripts)

# Save everything in one .rds file
saveRDS(object = raw_data,file = file.path(dataset_folder,"raw_data.rds"))
```

```{r load_data}
raw_data = readRDS(file.path(dataset_folder,"raw_data.rds"))
# names(raw_data)
```

```{r preprocess_covariates}
# Delete '*C' rows and store them for validation in further
c_rows <- grep(pattern = 'C', x = rownames(raw_data$covariates), value = TRUE)
processed_covariates <- raw_data$covariates[-which(rownames(raw_data$covariates) %in% c_rows), ]
```

```{r preprocess_exposures}
# ...
```

```{r preprocess_metabolities}
# ...
```

```{r preprocess_methylation}
# ...
```

```{r preprocess_proteins}
# ...
```

```{r preprocess_transcripts}
# ...
```


## Exploring dataset

```{r exploring_dataset}
# ...
```


